### ISSUE TITLE
Submit your portfolio link below!

### ISSUE THREAD

**Issue by bluelotus03** [GWC-UNCC/Intro-to-ReactJS-Portfolio-Projects#1]
Make sure you have deployed your portfolio and submit the link of your live portfolio. We will list it as a project on our GWC portfolio page and share it in our recap post on social media. 

**Just know it does not need to be perfect to share, and you can always update it.** 

If you're not ready to submit during our Portfolio Social, we will still keep submissions open for a few more days! And remember, you can take your time and work on your portfolio as long as you like. Even if it is not submitted in time to be included on our page, you should share it and be proud of your work!

**Comment by zshawar** [comment]
Zaina Shawar https://gwc-react-portfolio-zshawar.vercel.app/

**Comment by bluelotus03** [comment]
Ashley Harmon https://flx0u.csb.app/

**Comment by michecamacho** [comment]
Michelle Camacho

https://gwc-react-portfolio-michecamacho.vercel.app/

**Comment by bluelotus03** [comment]
Submissions are now closed. Thank you for sharing! 💜
